Fix sale price not indexing and custom_attribute not exporting
doofinder/doofinder-woocommerce pull request #253
Opened 2024-02-01 16:37 UTC by juan-gm

This PR fixes issues https://github.com/doofinder/support/issues/2037 and https://github.com/doofinder/support/issues/2079

The first issue was caused by the code deleting all of the elements in the custom_attributes array if they didn't have the key "name". To fix it we check first if we are setting an empty array as the custom attrbiute, and if so we leave the original, full array. 

The second was caused by the wordpress funcion "get_sale_price" from WC_Product not returning a value. We believe this happens when a product has variants (https://stackoverflow.com/a/51065777). We are making a fix by calculating the sales price ourselves, looking at the regular price and the price.

2024-02-01 17:50 UTC, sofia-doofinder requested changes

2024-02-01 17:50 UTC, sofia-doofinder commented on doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
> +                }
@juan-gm igual me estoy liando pero este caso no sería al revés? o igual es que la comprobación se me hace rara.. $name_column va a tener un array vacío si no encuentra nada y un array con valores si encuentra algo, entonces, el if no debería ser algo como esto?:

```suggestion
                if (!empty($name_column)) {
                    $data_with_attr[$fieldKey] = $name_column;
                }    
```

tal y como lo tienes creo que es al contrario, no? que si no hay $name_column entonces estás sobreescribiendo el valor?

2024-02-02 08:20 UTC, juan-gm commented on doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
> +                }
cierto lo cambio! Gracias

2024-02-02 09:06 UTC, sofia-doofinder approved these changes

2024-02-02 10:31 UTC, eduardogomez97 approved these changes

2024-02-05 11:36 UTC, merged