PLUGINRANGERS-535 | Improved Doofinder script storage in the database
doofinder/doofinder-woocommerce pull request #298
Opened 2024-06-25 15:11 UTC by davidmolinacano

Required by:

- https://github.com/doofinder/dooplugins/issues/535
- https://github.com/doofinder/support/issues/2493

2024-06-26 12:28 UTC, eduardogomez97 approved these changes
Great job!

2024-06-27 08:09 UTC, sofia-doofinder requested changes

2024-06-27 08:09 UTC, sofia-doofinder commented on doofinder-for-woocommerce/includes/settings/class-accessors.php
> +    private static function get_correct_script_version( $language ) {
Si puedes comenta por qué necesitamos esta función, quizás se le pueda poner también un nombre un poco más descriptivo como `get_script_backwards compatibility` o algo así, y en la descripción de la issue comentar el problema que tenemos que antes teníamos un script por cada idioma y ahora es uno común y le añadimos el idioma a posteriori.

2024-06-27 08:09 UTC, sofia-doofinder commented on doofinder-for-woocommerce/includes/settings/class-accessors.php
> +    private static function maybe_prepend_extra_config( $base_script, $language ) {
y en esta función también vendría bien documentar por qué el caso de `str_contains( $base_script, 'doofinderApp' ) ) ` para que no se nos olvide que esto es para evitar problemas por si alguien tiene definido el idioma en el script

2024-07-01 09:59 UTC, davidmolinacano commented on doofinder-for-woocommerce/includes/settings/class-accessors.php
> +    private static function get_correct_script_version( $language ) {
Hecho en: https://github.com/doofinder/doofinder-woocommerce/pull/298/commits/5baf2c6c1aec2af4b21b724c7e8d326d0041c650

2024-07-01 09:59 UTC, davidmolinacano commented on doofinder-for-woocommerce/includes/settings/class-accessors.php
> +    private static function maybe_prepend_extra_config( $base_script, $language ) {
Hecho en: https://github.com/doofinder/doofinder-woocommerce/pull/298/commits/5baf2c6c1aec2af4b21b724c7e8d326d0041c650

2024-07-01 10:00 UTC, davidmolinacano commented
Además de los comentarios, he cubierto otro edge-case que podía haber que era que en caso de tener el script nuevo, pero con idiomas en la BD, podría coger siempre el caso default, cuando para los migrados con anterioridad no debería ser así:

https://github.com/doofinder/doofinder-woocommerce/pull/298/commits/5baf2c6c1aec2af4b21b724c7e8d326d0041c650

2024-07-01 10:24 UTC, pedromcp90 approved these changes
Very good job!! :1st_place_medal:

2024-07-01 12:24 UTC, sofia-doofinder approved these changes
great job! :rocket:

2024-07-01 13:36 UTC, davidmolinacano commented on doofinder-for-woocommerce/includes/class-js-layer.php
> +        */
Básicamente eliminar todo lo referente al script antiguo, así el código quedaría muchísimo más limpio y legible :smile:

2024-07-01 14:57 UTC, merged