PLUGINRANGERS-304 | Applied automatic code style changes by WooCommerce lint, part 2
doofinder/doofinder-woocommerce pull request #307
Opened 2024-07-24 13:33 UTC by davidmolinacano

Required by:

- https://github.com/doofinder/doofinder-woocommerce/issues/304

2024-07-26 14:16 UTC, sofia-doofinder requested changes

2024-07-26 14:16 UTC, sofia-doofinder commented on doofinder-for-woocommerce/includes/class-setup-wizard.php
> +		$this->process_all_languages = empty( $this->language->get_languages() ) ? false : true;
esto se queda duplicado?

2024-07-26 14:16 UTC, sofia-doofinder commented on phpcs.xml
> +        <!-- TODO (davidmolinacano): To be removed in the future -->
hasta cuando debe estar eso ahí? está relacionado con este refactor o es por otra cosa? lo digo porque si es para el futuro quizás mejor decir hasta cuando :sweat_smile:

2024-07-26 14:16 UTC, sofia-doofinder commented on doofinder-for-woocommerce/includes/class-setup-wizard.php
> +							<!-- TODO: translate this string since the domain was wrong, doofinder_for_wp -->
no entiendo bien este todo, me puedes dar un poco de contexto please?

2024-07-29 06:44 UTC, davidmolinacano commented on doofinder-for-woocommerce/includes/class-setup-wizard.php
> +		$this->process_all_languages = empty( $this->language->get_languages() ) ? false : true;
Ayyy esto ha debido ser una mala resolución de conflictos, lo siento :pray:

2024-07-29 06:55 UTC, davidmolinacano commented on phpcs.xml
> +        <!-- TODO (davidmolinacano): To be removed in the future -->
La idea es quitarlo cuando resolvamos los más básicos. Es altamente probable que estos no se requieran para pasar la validación de WooCommerce, así que se dejarán para una segunda ronda más adelante ya que, además, requieren un refactor más grande. En resumen, la idea es excluir los errores más complejos o más estrictos y centrarnos en esta "primera ronda" en los sencillos y necesarios.

2024-07-29 06:58 UTC, davidmolinacano commented on doofinder-for-woocommerce/includes/class-setup-wizard.php
> +							<!-- TODO: translate this string since the domain was wrong, doofinder_for_wp -->
Básicamente que este string, probablemente debido a un error, no tenía el contexto correcto (`wordpress-doofinder`) y en su lugar tenía doofinder_for_wp que quizás era uno del antiguo plugin asumo. Por suerte, no tenia ninguna traducción asociada, pero lo ideal sería añadirla en un futuro :smile:

2024-07-29 07:05 UTC, davidmolinacano commented on doofinder-for-woocommerce/includes/class-setup-wizard.php
> +							<!-- TODO: translate this string since the domain was wrong, doofinder_for_wp -->
Vale, parece que no hay traducciones de nada realmente actualmente, así que borro el comentario. Por lo que veo se han añadido cadenas traducibles para traducir en un futuro.

2024-07-29 07:08 UTC, davidmolinacano commented on doofinder-for-woocommerce/includes/class-setup-wizard.php
> +		$this->process_all_languages = empty( $this->language->get_languages() ) ? false : true;
Arreglado en: https://github.com/doofinder/doofinder-woocommerce/pull/307/commits/8abf35da975dc5352a9436709af46d8d59b1921a

2024-07-29 07:08 UTC, davidmolinacano commented on phpcs.xml
> +        <!-- TODO (davidmolinacano): To be removed in the future -->
Igualmente he añadido más información en: https://github.com/doofinder/doofinder-woocommerce/pull/307/commits/97ac8436944df97474633dd5af10b4cbb310c983

2024-07-29 08:47 UTC, pedromcp90 approved these changes
Great work! :medal_military: :trophy:

2024-07-29 12:30 UTC, sofia-doofinder approved these changes

2024-07-29 13:30 UTC, merged